var menudata={children:[
{text:'Main Page',url:'index.html'},
{text:'Files',url:'files.html',children:[
{text:'File List',url:'files.html'},
{text:'File Members',url:'globals.html',children:[
{text:'All',url:'globals.html',children:[
{text:'a',url:'globals.html#index_a'},
{text:'b',url:'globals.html#index_b'},
{text:'c',url:'globals.html#index_c'},
{text:'d',url:'globals.html#index_d'},
{text:'f',url:'globals.html#index_f'},
{text:'g',url:'globals.html#index_g'},
{text:'l',url:'globals.html#index_l'},
{text:'m',url:'globals.html#index_m'},
{text:'n',url:'globals.html#index_n'},
{text:'o',url:'globals.html#index_o'},
{text:'p',url:'globals.html#index_p'},
{text:'r',url:'globals.html#index_r'},
{text:'s',url:'globals.html#index_s'},
{text:'t',url:'globals.html#index_t'},
{text:'w',url:'globals.html#index_w'},
{text:'z',url:'globals.html#index_z'}]},
{text:'Functions/Subroutines',url:'globals_func.html',children:[
{text:'a',url:'globals_func.html#index_a'},
{text:'b',url:'globals_func.html#index_b'},
{text:'c',url:'globals_func.html#index_c'},
{text:'d',url:'globals_func.html#index_d'},
{text:'f',url:'globals_func.html#index_f'},
{text:'g',url:'globals_func.html#index_g'},
{text:'l',url:'globals_func.html#index_l'},
{text:'m',url:'globals_func.html#index_m'},
{text:'n',url:'globals_func.html#index_n'},
{text:'o',url:'globals_func.html#index_o'},
{text:'p',url:'globals_func.html#index_p'},
{text:'r',url:'globals_func.html#index_r'},
{text:'s',url:'globals_func.html#index_s'},
{text:'t',url:'globals_func.html#index_t'},
{text:'w',url:'globals_func.html#index_w'},
{text:'z',url:'globals_func.html#index_z'}]},
{text:'Variables',url:'globals_vars.html'},
{text:'Macros',url:'globals_defs.html'}]}]}]}
