################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/C-assimilation.c \
../src/C-deciduous-partitioning.c \
../src/C-evergreen-partitioning.c \
../src/C-fruit-partitioning.c \
../src/CN-allocation.c \
../src/N-assimilation.c \
../src/Penman_Monteith.c \
../src/allometry.c \
../src/aut_respiration.c \
../src/balance.c \
../src/biomass.c \
../src/canopy_evapotranspiration.c \
../src/canopy_interception.c \
../src/canopy_net_radiation.c \
../src/canopy_radiation_lw_band.c \
../src/canopy_radiation_sw_band.c \
../src/canopy_sensible_heat.c \
../src/canopy_temperature.c \
../src/cell_model.c \
../src/cell_model_check_balance.c \
../src/common.c \
../src/compare.c \
../src/cue.c \
../src/decomposition.c \
../src/dendrometry.c \
../src/establishment.c \
../src/evapotranspiration.c \
../src/fluxes.c \
../src/g-function.c \
../src/heat_fluxes.c \
../src/het_respiration.c \
../src/initialization.c \
../src/lai.c \
../src/leaf_fall.c \
../src/litter_model.c \
../src/litter_model_check_balance.c \
../src/littering.c \
../src/logger.c \
../src/main.c \
../src/management.c \
../src/matrix.c \
../src/met_data.c \
../src/meteo.c \
../src/modifiers.c \
../src/mortality.c \
../src/nc.c \
../src/new_forest_tree_class.c \
../src/output.c \
../src/peak_lai.c \
../src/phenology.c \
../src/photosynthesis.c \
../src/print.c \
../src/print_output.c \
../src/regeneration.c \
../src/remove_tree_class.c \
../src/settings.c \
../src/snow.c \
../src/soil_evaporation.c \
../src/soil_model.c \
../src/soil_model_check_balance.c \
../src/soil_nitrogen_balance.c \
../src/soil_radiation_sw_band.c \
../src/soil_respiration.c \
../src/soil_settings.c \
../src/soil_water_balance.c \
../src/structure.c \
../src/topo.c \
../src/tree_model.c \
../src/tree_model_check_balance.c \
../src/turnover.c \
../src/turnover_Marconi.c \
../src/utility.c \
../src/water_balance.c \
../src/wue.c 

OBJS += \
./src/C-assimilation.o \
./src/C-deciduous-partitioning.o \
./src/C-evergreen-partitioning.o \
./src/C-fruit-partitioning.o \
./src/CN-allocation.o \
./src/N-assimilation.o \
./src/Penman_Monteith.o \
./src/allometry.o \
./src/aut_respiration.o \
./src/balance.o \
./src/biomass.o \
./src/canopy_evapotranspiration.o \
./src/canopy_interception.o \
./src/canopy_net_radiation.o \
./src/canopy_radiation_lw_band.o \
./src/canopy_radiation_sw_band.o \
./src/canopy_sensible_heat.o \
./src/canopy_temperature.o \
./src/cell_model.o \
./src/cell_model_check_balance.o \
./src/common.o \
./src/compare.o \
./src/cue.o \
./src/decomposition.o \
./src/dendrometry.o \
./src/establishment.o \
./src/evapotranspiration.o \
./src/fluxes.o \
./src/g-function.o \
./src/heat_fluxes.o \
./src/het_respiration.o \
./src/initialization.o \
./src/lai.o \
./src/leaf_fall.o \
./src/litter_model.o \
./src/litter_model_check_balance.o \
./src/littering.o \
./src/logger.o \
./src/main.o \
./src/management.o \
./src/matrix.o \
./src/met_data.o \
./src/meteo.o \
./src/modifiers.o \
./src/mortality.o \
./src/nc.o \
./src/new_forest_tree_class.o \
./src/output.o \
./src/peak_lai.o \
./src/phenology.o \
./src/photosynthesis.o \
./src/print.o \
./src/print_output.o \
./src/regeneration.o \
./src/remove_tree_class.o \
./src/settings.o \
./src/snow.o \
./src/soil_evaporation.o \
./src/soil_model.o \
./src/soil_model_check_balance.o \
./src/soil_nitrogen_balance.o \
./src/soil_radiation_sw_band.o \
./src/soil_respiration.o \
./src/soil_settings.o \
./src/soil_water_balance.o \
./src/structure.o \
./src/topo.o \
./src/tree_model.o \
./src/tree_model_check_balance.o \
./src/turnover.o \
./src/turnover_Marconi.o \
./src/utility.o \
./src/water_balance.o \
./src/wue.o 

C_DEPS += \
./src/C-assimilation.d \
./src/C-deciduous-partitioning.d \
./src/C-evergreen-partitioning.d \
./src/C-fruit-partitioning.d \
./src/CN-allocation.d \
./src/N-assimilation.d \
./src/Penman_Monteith.d \
./src/allometry.d \
./src/aut_respiration.d \
./src/balance.d \
./src/biomass.d \
./src/canopy_evapotranspiration.d \
./src/canopy_interception.d \
./src/canopy_net_radiation.d \
./src/canopy_radiation_lw_band.d \
./src/canopy_radiation_sw_band.d \
./src/canopy_sensible_heat.d \
./src/canopy_temperature.d \
./src/cell_model.d \
./src/cell_model_check_balance.d \
./src/common.d \
./src/compare.d \
./src/cue.d \
./src/decomposition.d \
./src/dendrometry.d \
./src/establishment.d \
./src/evapotranspiration.d \
./src/fluxes.d \
./src/g-function.d \
./src/heat_fluxes.d \
./src/het_respiration.d \
./src/initialization.d \
./src/lai.d \
./src/leaf_fall.d \
./src/litter_model.d \
./src/litter_model_check_balance.d \
./src/littering.d \
./src/logger.d \
./src/main.d \
./src/management.d \
./src/matrix.d \
./src/met_data.d \
./src/meteo.d \
./src/modifiers.d \
./src/mortality.d \
./src/nc.d \
./src/new_forest_tree_class.d \
./src/output.d \
./src/peak_lai.d \
./src/phenology.d \
./src/photosynthesis.d \
./src/print.d \
./src/print_output.d \
./src/regeneration.d \
./src/remove_tree_class.d \
./src/settings.d \
./src/snow.d \
./src/soil_evaporation.d \
./src/soil_model.d \
./src/soil_model_check_balance.d \
./src/soil_nitrogen_balance.d \
./src/soil_radiation_sw_band.d \
./src/soil_respiration.d \
./src/soil_settings.d \
./src/soil_water_balance.d \
./src/structure.d \
./src/topo.d \
./src/tree_model.d \
./src/tree_model_check_balance.d \
./src/turnover.d \
./src/turnover_Marconi.d \
./src/utility.d \
./src/water_balance.d \
./src/wue.d 


# Each subdirectory must supply rules for building sources it contributes
src/%.o: ../src/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -I"/home/alessio-cmcc/git/3D-CMCC-LAND/software/3D-CMCC-Forest-Model/headers" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


